name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          npm install
          npm run-script build
        env:
          REACT_APP_GPT_API_KEY: ${{ secrets.REACT_APP_GPT_API_KEY }}

      - name: Deploy
        uses: HackathonChattyAI/github-pages-deploy-action@releases/v3
        with:
          BRANCH: gh-pages
          FOLDER: build
